pri = input()
seg = input()
ter = input()
if pri == 'vertebrado' and seg == 'ave' and ter == 'carnivoro': print('aguia')
elif pri == 'vertebrado' and seg == 'ave' and ter == 'onivoro': print('pomba')
elif pri == 'vertebrado' and seg == 'mamifero' and ter == 'onivoro': print('homem')
elif pri == 'vertebrado' and seg == 'mamifero' and ter == 'herbivoro': print('vaca')
elif pri == 'invertebrado' and seg == 'inseto' and ter == 'hematofago': print('pulga')
elif pri == 'invertebrado' and seg == 'inseto' and ter == 'herbivoro': print('lagarta')
elif pri == 'invertebrado' and seg == 'anelideo' and ter == 'onivoro': print('minhoca')
elif pri == 'invertebrado' and seg == 'anelideo' and ter == 'hematofago': print('sanguessuga')
